# Generated by Django 5.1 on 2024-08-26 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowerBouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название букета')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('flower_count', models.PositiveIntegerField(default=1, verbose_name='Количество цветков')),
                ('color', models.CharField(max_length=255, verbose_name='Основной цвет')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Изображение')),
                ('is_exists', models.BooleanField(default=True, verbose_name='Доступность для заказа')),
            ],
            options={
                'verbose_name': 'Букет',
                'verbose_name_plural': 'Букеты',
            },
        ),
        migrations.CreateModel(
            name='GreenType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название типа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('poison', models.BooleanField(default=False, verbose_name='Ядовитость')),
            ],
            options={
                'verbose_name': 'Тип растения',
                'verbose_name_plural': 'Типы растений',
            },
        ),
        migrations.CreateModel(
            name='HolidayCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название коллекции')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date_start', models.DateField(auto_now_add=True, verbose_name='Дата начала')),
                ('date_end', models.DateField(auto_now_add=True, verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Коллекция к празднику',
                'verbose_name_plural': 'Коллекции к праздникам',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_firstname', models.CharField(max_length=255, verbose_name='Фамилия заказчика')),
                ('buyer_name', models.CharField(max_length=255, verbose_name='Имя заказчика')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий')),
                ('delivery_address', models.CharField(max_length=255, verbose_name='Адрес доставки')),
                ('delivery_type', models.CharField(choices=[('SH', 'Магазин'), ('CR', 'Курьер')], default='SH', max_length=2, verbose_name='Способ доставки')),
                ('date_start', models.DateField(auto_now_add=True, verbose_name='Дата начала')),
                ('finish', models.BooleanField(default=False, verbose_name='Выполнен')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('agent_firstname', models.CharField(max_length=255, verbose_name='Фамилия представителя')),
                ('agent_name', models.CharField(max_length=255, verbose_name='Имя представителя')),
                ('phone', models.CharField(max_length=16, verbose_name='Телефон')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('is_exists', models.BooleanField(default=True, verbose_name='Доступность')),
                ('country', models.CharField(max_length=255, verbose_name='Страна отгрузки')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='PosOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Скидка на товар')),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flower_shop.flowerbouquet', verbose_name='Букет')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flower_shop.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='bouquet',
            field=models.ManyToManyField(through='flower_shop.PosOrder', to='flower_shop.flowerbouquet', verbose_name='Букет'),
        ),
        migrations.CreateModel(
            name='PosSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('green', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flower_shop.greentype', verbose_name='Растение')),
            ],
            options={
                'verbose_name': 'Позиция поставки',
                'verbose_name_plural': 'Позиции поставки',
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_supply', models.DateTimeField(verbose_name='Дата поставки')),
                ('green', models.ManyToManyField(through='flower_shop.PosSupply', to='flower_shop.greentype', verbose_name='Цветы')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flower_shop.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Поставка',
                'verbose_name_plural': 'Поставки',
            },
        ),
        migrations.AddField(
            model_name='possupply',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flower_shop.supply', verbose_name='Поставка'),
        ),
    ]
